### ISSUE TITLE
APRS tracker building 

### ISSUE THREAD

**Issue by hasithperera** [W8CUL/ARC-HAB#5]
- [ ] DR818 V power and low voltage testing
- [ ] 3.3 V power systems testing
- [ ] Li ion BMS testing
- [ ] Atmega 328PB low power testing
- [ ] Daughter board interface specs
- [ ] Ground testing for a low power system
- [ ] CW module
  - [ ] Pico testing
  - [ ] grid conversion algorithm
  - [ ] landing and power saver mode detection
